// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc3PFzElFMO28DKEEoCHKvKilm3qyaTQE',
    appId: '1:942377143150:web:11e0e041c0d82c961b4f7f',
    messagingSenderId: '942377143150',
    projectId: 'ecommerce-clean-arch',
    authDomain: 'ecommerce-clean-arch.firebaseapp.com',
    storageBucket: 'ecommerce-clean-arch.firebasestorage.app',
    measurementId: 'G-SESK6N4KWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQEgSWwNNBsRYrBKyfpmkBiiaraeRsqO4',
    appId: '1:942377143150:android:2e65e0b48ae20c2d1b4f7f',
    messagingSenderId: '942377143150',
    projectId: 'ecommerce-clean-arch',
    storageBucket: 'ecommerce-clean-arch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeL_OCBlWhbURCAcDzDd-RPkQTmgcHuXI',
    appId: '1:942377143150:ios:7d6d9cdb612750d51b4f7f',
    messagingSenderId: '942377143150',
    projectId: 'ecommerce-clean-arch',
    storageBucket: 'ecommerce-clean-arch.firebasestorage.app',
    iosBundleId: 'com.example.mvvmFruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeL_OCBlWhbURCAcDzDd-RPkQTmgcHuXI',
    appId: '1:942377143150:ios:7d6d9cdb612750d51b4f7f',
    messagingSenderId: '942377143150',
    projectId: 'ecommerce-clean-arch',
    storageBucket: 'ecommerce-clean-arch.firebasestorage.app',
    iosBundleId: 'com.example.mvvmFruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9HFScOwbyGZyzUsequQn_q-G40ZxuxkE',
    appId: '1:942377143150:web:6905ef8079c485e91b4f7f',
    messagingSenderId: '942377143150',
    projectId: 'ecommerce-clean-arch',
    authDomain: 'ecommerce-clean-arch.firebaseapp.com',
    storageBucket: 'ecommerce-clean-arch.firebasestorage.app',
    measurementId: 'G-N01DDMTXJS',
  );
}
